### ISSUE TITLE
oauth.accessToken

### ISSUE THREAD

**Issue by leninrivG** [IntuitDeveloper/SampleApp-CRUD-Java#2]
how can i get the oauth.accessToken and the oauth.accessTokenSecret for the config.properties file?
please help

**Comment by diana-derose** [comment]
Hi, Refer this blog post to see how to generate oauth tokens using OAuth Playground
https://developer.intuit.com/hub/blog/2016/04/25/quick-start-to-quickbooks-online-rest-api-with-oauth1-0
Additionally, you can also run this app to get them https://github.com/IntuitDeveloper/oauth-java
