### ISSUE TITLE
Is there any future plan to support QBO Projects CRUD through the API?

### ISSUE THREAD

**Issue by jaGarcia** [IntuitDeveloper/SampleApp-CRUD-Java#6]
Currently, even if I link payments and refunds to an invoice, as soon as a user links that invoice to a Project is delinks all of the txn's.  So, being able to control the order of Project creation to ensure the linkages are maintained is fairly important/critical...

**Comment by diana-derose** [comment]
Hi @jaGarcia  - Projects API is in the roadmap for our next generation APIs. I don't have dates yet on its availability though. I will pass on your feedback to the team working on this.

If you can also vote on this feature here, it will be great-
https://intuitdevelopergroup.uservoice.com/forums/182764-intuit-developer-group/suggestions/34392808-quickbooks-online-projects

**Comment by jaGarcia** [comment]
Thanks Diana.  I added my vote.

-Andrew
