### ISSUE TITLE
Line Item Order for Estimates

### ISSUE THREAD

**Issue by husani0NL9** [IntuitDeveloper/SampleApp-CRUD-Java#7]
I am currently building a Java web application in Eclipse and I'm trying to integrate the QuickBooks Online API into it. I have successfully added the QuickBooks Java SDK and I am using code from this project.

Unfortunately, when creating an Estimate, setting the Line Number ( e.g., line.setLineNum(new BigInteger("1")); ) seems to have no affect on the order of the Line Items.

The Line Item order seems to be random regardless of what line numbers I set.

Please let me know if there's something I'm missing or if there's possibly an issue with the SDK.

**Comment by diana-derose** [comment]
Hi @husani0NL9  - This is currently not supported by the API, lineNum attribute is returned back in the response to indicate the item order, setting it in the request has no effect on the backend as of now. We have created an enhancement request to add this feature in.

Also, for API related issues, please reach out to us at https://help.developer.intuit.com/s/ to get faster response.
