### ISSUE TITLE
Please edit the readme file with some steps to setup the config.properties

### ISSUE THREAD

**Issue by tbvinh** [IntuitDeveloper/SampleApp-CRUD-Java#8]
Create a sandbox app with three information:

1. App Id= xxxxx
2. "Client ID=xxx" 
3. "Client Secret=yyyy"

But I cannot know how to fill them into the config.properties.
Please help me.

==================the config.properties=============
#For OAuth2 app set oauth.type=2
oauth.type=1

#OAuth2 access token
oauth2.accessToken = 

#company id or realmId
company.id=

#OAuth1 keys
app.token=
consumer.key=
consumer.secret=
oauth.accessToken=
oauth.accessTokenSecret=
==================END of the config.properties=============

**Comment by sriramvnc** [comment]
did you found the answer ?

**Comment by nimisha84** [comment]
Please fill up  the above 3 props- 
    App Id= xxxxx
    "Client ID=xxx"
    "Client Secret=yyyy"
They are available on developer.intuit.com->login->dashboard->your app ->sandbox or production tabs
